---
AllCops:
  Exclude:
    - "bin/*"
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/LineLength:
  Max: 120
