#!/usr/bin/env ruby
# frozen_string_literal: true
# typed: strict

require "project_templates"
require "sorbet-runtime"
require "pry"

module ProjectTemplates
  app = App.configure(ARGV)
  app.run
end
